// Code generated by mockery v2.53.4. DO NOT EDIT.

package repositories

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	srcrepositories "github.com/verizhang/billing-engine/src/repositories"
)

// UnitOfWork is an autogenerated mock type for the UnitOfWork type
type UnitOfWork struct {
	mock.Mock
}

type UnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitOfWork) EXPECT() *UnitOfWork_Expecter {
	return &UnitOfWork_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *UnitOfWork) Begin(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnitOfWork_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type UnitOfWork_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnitOfWork_Expecter) Begin(ctx interface{}) *UnitOfWork_Begin_Call {
	return &UnitOfWork_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *UnitOfWork_Begin_Call) Run(run func(ctx context.Context)) *UnitOfWork_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UnitOfWork_Begin_Call) Return(_a0 *gorm.DB, _a1 error) *UnitOfWork_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UnitOfWork_Begin_Call) RunAndReturn(run func(context.Context) (*gorm.DB, error)) *UnitOfWork_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: tx
func (_m *UnitOfWork) Commit(tx *gorm.DB) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type UnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *UnitOfWork_Expecter) Commit(tx interface{}) *UnitOfWork_Commit_Call {
	return &UnitOfWork_Commit_Call{Call: _e.mock.On("Commit", tx)}
}

func (_c *UnitOfWork_Commit_Call) Run(run func(tx *gorm.DB)) *UnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *UnitOfWork_Commit_Call) Return(_a0 error) *UnitOfWork_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnitOfWork_Commit_Call) RunAndReturn(run func(*gorm.DB) error) *UnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// LoanRepository provides a mock function with given fields: tx
func (_m *UnitOfWork) LoanRepository(tx *gorm.DB) srcrepositories.LoanRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for LoanRepository")
	}

	var r0 srcrepositories.LoanRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) srcrepositories.LoanRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(srcrepositories.LoanRepository)
		}
	}

	return r0
}

// UnitOfWork_LoanRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoanRepository'
type UnitOfWork_LoanRepository_Call struct {
	*mock.Call
}

// LoanRepository is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *UnitOfWork_Expecter) LoanRepository(tx interface{}) *UnitOfWork_LoanRepository_Call {
	return &UnitOfWork_LoanRepository_Call{Call: _e.mock.On("LoanRepository", tx)}
}

func (_c *UnitOfWork_LoanRepository_Call) Run(run func(tx *gorm.DB)) *UnitOfWork_LoanRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *UnitOfWork_LoanRepository_Call) Return(_a0 srcrepositories.LoanRepository) *UnitOfWork_LoanRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnitOfWork_LoanRepository_Call) RunAndReturn(run func(*gorm.DB) srcrepositories.LoanRepository) *UnitOfWork_LoanRepository_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentRepository provides a mock function with given fields: tx
func (_m *UnitOfWork) PaymentRepository(tx *gorm.DB) srcrepositories.PaymentRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for PaymentRepository")
	}

	var r0 srcrepositories.PaymentRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) srcrepositories.PaymentRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(srcrepositories.PaymentRepository)
		}
	}

	return r0
}

// UnitOfWork_PaymentRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentRepository'
type UnitOfWork_PaymentRepository_Call struct {
	*mock.Call
}

// PaymentRepository is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *UnitOfWork_Expecter) PaymentRepository(tx interface{}) *UnitOfWork_PaymentRepository_Call {
	return &UnitOfWork_PaymentRepository_Call{Call: _e.mock.On("PaymentRepository", tx)}
}

func (_c *UnitOfWork_PaymentRepository_Call) Run(run func(tx *gorm.DB)) *UnitOfWork_PaymentRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *UnitOfWork_PaymentRepository_Call) Return(_a0 srcrepositories.PaymentRepository) *UnitOfWork_PaymentRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnitOfWork_PaymentRepository_Call) RunAndReturn(run func(*gorm.DB) srcrepositories.PaymentRepository) *UnitOfWork_PaymentRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: tx
func (_m *UnitOfWork) Rollback(tx *gorm.DB) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type UnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *UnitOfWork_Expecter) Rollback(tx interface{}) *UnitOfWork_Rollback_Call {
	return &UnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", tx)}
}

func (_c *UnitOfWork_Rollback_Call) Run(run func(tx *gorm.DB)) *UnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *UnitOfWork_Rollback_Call) Return(_a0 error) *UnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnitOfWork_Rollback_Call) RunAndReturn(run func(*gorm.DB) error) *UnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnitOfWork creates a new instance of UnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWork {
	mock := &UnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
